DIRECTORY = "data/large"

PEOPLE_FILE_NAME = "people.csv"
MOVIES_FILE_NAME = "movies.csv"
STARS_FILE_NAME = "stars.csv"

DOLLAR_SIGN = "$"
PERSON_PREFIX = "P-"
MOVIE_PREFIX = "M-"

PATH_CONNECTOR = " -> "
DIVIDING_OUTPUT_LINE = "---" * 30
TEXT_GREEN_COLOR = "\033[92m"
TEXT_YELLOW_COLOR = "\033[93m"
TEXT_DEFAULT_COLOR = "\033[0m"